
services:
  mysqldb:
    image: mysql:8.0.2
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./app/sql/modelos.sql:/docker-entrypoint-initdb.d/modelos.sql

  app:
    depends_on:
      - mysqldb
    build: ./app
    restart: on-failure
    env_file: .env
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false   &sslMode=DISABLED   &allowPublicKeyRetrieval=true   &serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}

volumes:
  db: